version: '3.1'
services:
  db:
    image: mysql
    container_name: spring_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - spring_data:/var/lib/mysql

volumes:
  spring_data: