server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: springboot-project
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, metrics, health, prometheus


  info:
    env:
      enabled: true

info:
  application:
    name: Spring Boot project
    description: Project for studies spring boot
    author: Tiago Barbosa
    github: https://github.com/tiagoBarbosaF/springboot